services:
  postgres-db:
    image: postgres:14-alpine
    container_name: home-inventory-postgres-db
    networks:
      - home-inventory
    restart: always
    environment:
      POSTGRES_DB: home_inventory_dev 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
networks:
  home-inventory:
