# fly.toml file generated for young-wind-7044 on 2022-05-01T14:58:08-05:00

app = "young-wind-7044"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
strategy = "bluegreen"
release_command = "/app/bin/home_inventory eval \"HomeInventory.Release.migrate\""

[env]
CANONICAL_URL = "young-wind-7044.internal:8080"
STATIC_URL = "young-wind-7044.internal:8080"
PORT = "8080"
DATABASE_POOL_SIZE = "40"
DATABASE_SSL = "false"
DEBUG_ERRORS = "true"

[experimental]
allowed_public_ports = []
auto_rollback = true

# [[services]]
#   http_checks = []
#   internal_port = 8080
#   processes = ["app"]
#   protocol = "tcp"
#   script_checks = []

#   [services.concurrency]
#     hard_limit = 25
#     soft_limit = 20
#     type = "connections"

#   [[services.ports]]
#     force_https = true
#     handlers = ["http"]
#     port = 80

#   [[services.ports]]
#     handlers = ["tls", "http"]
#     port = 443

#   [[services.tcp_checks]]
#     grace_period = "1s"
#     interval = "15s"
#     restart_limit = 0
#     timeout = "2s"
